### ISSUE TITLE
When I import the nestjs-pino library I get an exception.

### ISSUE THREAD

**Issue by yefersox** [mcollina/on-exit-leak-free#35]
on-exit-leak-free/index.js:11
const registry = new FinalizationRegistry(clear)
                 ^
ReferenceError: FinalizationRegistry is not defined
    at Object.<anonymous> (/Users/yefersongarcia/Desktop/vtex-checkout-headless-new/reg-ccom-cko-auth/node_modules/on-exit-leak-free/index.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)

Do you have any idea?

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by azrikahar** [comment]
@yefersox are you using Node version older than v14 by any chance? `FinalizationRegistry` requires 14 and above as mentioned in the README:

> Requires `WeakRef` and `FinalizationRegistry`, i.e. use Node v14+.
